[package]
name = "mirsa-driver"
version = "0.2.3"
edition = "2024"
publish = false

[dependencies]
mirsa_analysis = { package = "mirsa-analysis", path = "../analysis", version = "0.2.3" }
mirsa_core = { package = "mirsa-core", path = "../core", version = "0.2.3" }

[package.metadata.rust-analyzer]
rustc_private = true
