[workspace]
members = [
    "crates/driver",
    "crates/core",
    "crates/framework",
    "crates/relations",
    "crates/domains",
    "crates/contracts",
    "crates/analysis",
]
resolver = "2"

[package]
name = "mirsa"
version = "0.2.3"
edition = "2024"

description = "rust mir static analysis"
license = "MIT"

[dependencies]
mirsa_analysis = { package = "mirsa-analysis", path = "crates/analysis", version = "0.2.3" }
mirsa_contracts = { package = "mirsa-contracts", path = "crates/contracts", version = "0.2.3" }
mirsa_core = { package = "mirsa-core", path = "crates/core", version = "0.2.3" }
mirsa_domains = { package = "mirsa-domains", path = "crates/domains", version = "0.2.3" }
mirsa_framework = { package = "mirsa-framework", path = "crates/framework", version = "0.2.3" }
mirsa_relations = { package = "mirsa-relations", path = "crates/relations", version = "0.2.3" }

[package.metadata.rust-analyzer]
rustc_private = true
