[package]
name = "mirsa-contracts"
version = "0.2.1"
edition = "2024"
description = "Unsafe API contracts for mirsa"
license = "MIT"

[dependencies]
mirsa_domains = { package = "mirsa-domains", path = "../domains", version = "0.2.1" }
mirsa_framework = { package = "mirsa-framework", path = "../framework", version = "0.2.1" }
mirsa_relations = { package = "mirsa-relations", path = "../relations", version = "0.2.1" }

[package.metadata.rust-analyzer]
rustc_private = true
