[package]
name = "mirsa-domains"
version = "0.2.1"
edition = "2024"
description = "Abstract interpretation domains for mirsa"
license = "MIT"

[dependencies]
mirsa_framework = { package = "mirsa-framework", path = "../framework", version = "0.2.1" }
mirsa_relations = { package = "mirsa-relations", path = "../relations", version = "0.2.1" }

[package.metadata.rust-analyzer]
rustc_private = true
